version: "2"
linters:
  enable:
    - cyclop
    - funcorder
    - funlen
    - gosec
    - nestif
    - staticcheck
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
