run:
  timeout: 5m
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - gofmt
    - unused
    - cyclop
    - funlen
    - funcorder
    - gosec
    - paralleltes
    - nestif
issues:
  exclude-use-default: false
