services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-store-api
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - dev_network

  postgres:
    image: postgres:15
    container_name: dev_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - dev_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 5s

  redis:
      image: redis:7
      container_name: redis
      ports:
        - "6379:6379"
      command: [ "redis-server", "--appendonly", "yes" ]
      networks:
        - dev_network

networks:
  dev_network:
    driver: bridge
